"""add first model

Revision ID: df8741484c32
Revises: 
Create Date: 2024-04-25 11:40:27.660023

"""

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = "df8741484c32"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "farm_field",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "coordinates",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("datetime_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("datetime_modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
        schema="coffee",
    )
    op.create_geospatial_index(
        "idx_farm_field_coordinates",
        "farm_field",
        ["coordinates"],
        unique=False,
        schema="coffee",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_farm_field_coordinates",
        table_name="farm_field",
        schema="coffee",
        postgresql_using="gist",
        column_name="coordinates",
    )
    op.drop_geospatial_table("farm_field", schema="coffee")
    # ### end Alembic commands ###
