"""add computed area column

Revision ID: 669b300b5f3c
Revises: df8741484c32
Create Date: 2024-05-02 10:21:38.317264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669b300b5f3c'
down_revision = 'df8741484c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_field', sa.Column('area', sa.Float(), sa.Computed('ST_Area(coordinates, true)', ), nullable=True), schema='coffee')
    op.create_unique_constraint(None, 'farm_field', ['uuid'], schema='coffee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farm_field', schema='coffee', type_='unique')
    op.drop_column('farm_field', 'area', schema='coffee')
    # ### end Alembic commands ###
