"""add computed perimeter column

Revision ID: af5453ca27cd
Revises: 669b300b5f3c
Create Date: 2024-05-02 10:24:51.177408

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af5453ca27cd"
down_revision = "669b300b5f3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "farm_field",
        sa.Column(
            "perimeter",
            sa.Float(),
            sa.Computed(
                "ST_Perimeter(coordinates, true)",
            ),
            nullable=True,
            comment="Perimeter in meters",
        ),
        schema="coffee",
    )
    op.alter_column(
        "farm_field",
        "area",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Area in square meters",
        existing_nullable=True,
        schema="coffee",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "farm_field",
        "area",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Area in square meters",
        existing_nullable=True,
        schema="coffee",
    )
    op.drop_column("farm_field", "perimeter", schema="coffee")
    # ### end Alembic commands ###
